- name: Agregar tomcat group
  group:
   name: tomcat
  become: true
  when: ansible_os_family == "RedHat"

- name: Agregar "tomcat" user
  user:
   name: tomcat
   group: tomcat
   home: /home/projasmu/proyecto_manejo_control_acceso/roles/tomcat
   createhome: no
   system: yes
  become: true
  when: ansible_os_family == "RedHat"

- name: Descargar Tomcat
  get_url:
   url: "{{ tomcat_archive_url }}"
   dest: "{{ tomcat_archive_url }}"
  become: true
  when: ansible_os_family == "RedHat"

- name: Create a tomcat directory
  file:
   path: /home/projasmu/proyecto_manejo_control_acceso/roles/tomcat
   state: directory
   owner: tomcat
   group: tomcat
  become: true
  when: ansible_os_family == "RedHat"

- name: Extract tomcat archive
  unarchive:
   src: "{{ tomcat_archive_dest }}"
   dest: /usr/share/tomcat
   owner: tomcat
   group: tomcat
   remote_src: yes
   extra_opts: "--strip-components=1"
   creates: /usr/share/tomcat/bin
  become: true
  when: ansible_os_family == "RedHat"

- name: Copy tomcat service file
  template:
   src: templates/tomcat.service.j2
   dest: /etc/systemd/system/tomcat.service
  become: true
  when:
   - ansible_os_family == "RedHat"
   - ansible_service_mgr == "systemd"

- name: Start and enable tomcat
  ansible.builtin.command: systemctl start tomcat.service
  become: true
  when: ansible_os_family == "RedHat"
# tasks file for tomcat
